### ISSUE TITLE
Timestamp Issue

### ISSUE THREAD

**Issue by WeaveHubHQ** [andywalden/esm_event_lookaround#1]
Hi,

I'm having an issue running this script.  When I try to run it using esm_dns_lookaround.py -t '06/13/2017 08:00:00' -i 10.x.x.x, I get "error: unrecognized arguments: 08:00:00'".

Any ideas?  I tried changing the date around too to 13/06/2017 in case that was it but that didn't work either.

**Comment by andywalden** [comment]
Thanks for the report. If you use double quotes (unlike my example), then it should work. I will look to change out how the arguments are parsed in the meantime.

**Comment by WeaveHubHQ** [comment]
Thanks for the help, but that did not fix it for me. See below:

C:\Users\jlazerus\Downloads\esm_event_lookaround-master\esm_event_lookaround-mas
ter>C:\Users\jlazerus\AppData\Local\Programs\Python\Python36\python.exe
esm_dns_
lookaround.py -t "06-14-2017 00:00:00" -i 10.201.6.52
Traceback (most recent call last):
  File "esm_dns_lookaround.py", line 267, in calc_time_lookaround
    timestamp_o = datetime.strptime(timestamp, format)
  File
"C:\Users\jlazerus\AppData\Local\Programs\Python\Python36\lib\_strptime.p
y", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File
"C:\Users\jlazerus\AppData\Local\Programs\Python\Python36\lib\_strptime.p
y", line 362, in _strptime
    (data_string, format))
ValueError: time data '06-14-2017 00:00:00' does not match format '%m/%d/%Y
%H:%
M:%S'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "esm_dns_lookaround.py", line 312, in <module>
    main()
  File "esm_dns_lookaround.py", line 301, in main
    start_time, end_time = calc_time_lookaround(pargs.window, pargs.stime)
  File "esm_dns_lookaround.py", line 274, in calc_time_lookaround
    raise ValueError("Incorrect data format, should be '01/05/2017
02:00:05' - w
ith quotes.")
ValueError: Incorrect data format, should be '01/05/2017 02:00:05' - with
quotes
.


Jason S. Lazerus, M.S., GCFA, GPEN, GCIH, GCFE, GCED, GSEC

**Comment by WeaveHubHQ** [comment]
Ah, I used - instead of /.  That did it, thanks!!!


Jason S. Lazerus, M.S., GCFA, GPEN, GCIH, GCFE, GCED, GSEC
